-- ============================================
-- Load synthetic data for ygeiopolis database
-- Auto-generated by generate.py
-- Uses LOAD DATA LOCAL INFILE from CSVs
-- ============================================

USE ygeiopolis;

-- icd10
LOAD DATA LOCAL INFILE 'data/csv/load/icd10.csv'
INTO TABLE `icd10`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(icd10_code, description, category);

-- ken_categories
LOAD DATA LOCAL INFILE 'data/csv/load/ken_categories.csv'
INTO TABLE `ken_categories`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(category_letter, description);

-- ken
LOAD DATA LOCAL INFILE 'data/csv/load/ken.csv'
INTO TABLE `ken`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ken_code, description, base_cost, avg_length_of_stay, daily_surcharge_rate, category_letter);

-- active_substances
LOAD DATA LOCAL INFILE 'data/csv/load/active_substances.csv'
INTO TABLE `active_substances`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(substance_id, name);

-- drugs
LOAD DATA LOCAL INFILE 'data/csv/load/drugs.csv'
INTO TABLE `drugs`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(drug_id, ema_code, name, manufacturer);

-- drug_contains_substances
LOAD DATA LOCAL INFILE 'data/csv/load/drug_contains_substances.csv'
INTO TABLE `drug_contains_substances`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(drug_id, substance_id);

-- medical_procedures
LOAD DATA LOCAL INFILE 'data/csv/load/medical_procedures.csv'
INTO TABLE `medical_procedures`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(procedure_code, name, category, standard_duration, standard_cost);

-- exam_types
LOAD DATA LOCAL INFILE 'data/csv/load/exam_types.csv'
INTO TABLE `exam_types`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(exam_code, name);

-- operating_rooms
LOAD DATA LOCAL INFILE 'data/csv/load/operating_rooms.csv'
INTO TABLE `operating_rooms`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(room_id, room_name, room_type, floor, building);

-- departments
LOAD DATA LOCAL INFILE 'data/csv/load/departments.csv'
INTO TABLE `departments`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(dept_id, name, description, bed_count, floor, building, director_AMKA);

-- staff
LOAD DATA LOCAL INFILE 'data/csv/load/staff_doctors.csv'
INTO TABLE `staff`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(AMKA, first_name, last_name, date_of_birth, email, phone_number, hire_date, staff_type);

-- doctors
LOAD DATA LOCAL INFILE 'data/csv/load/doctors.csv'
INTO TABLE `doctors`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(AMKA, license_number, `rank`, specialty, supervisor_AMKA);

-- doctor_departments
LOAD DATA LOCAL INFILE 'data/csv/load/doctor_departments.csv'
INTO TABLE `doctor_departments`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(doctor_AMKA, dept_id);

-- Set department directors
UPDATE departments SET director_AMKA = '21320410429' WHERE dept_id = 1;
UPDATE departments SET director_AMKA = '72699994981' WHERE dept_id = 2;
UPDATE departments SET director_AMKA = '20005328538' WHERE dept_id = 3;
UPDATE departments SET director_AMKA = '82692990076' WHERE dept_id = 4;
UPDATE departments SET director_AMKA = '37618518626' WHERE dept_id = 5;
UPDATE departments SET director_AMKA = '33921883527' WHERE dept_id = 6;
UPDATE departments SET director_AMKA = '59208814319' WHERE dept_id = 7;
UPDATE departments SET director_AMKA = '38457202665' WHERE dept_id = 8;
UPDATE departments SET director_AMKA = '98992553946' WHERE dept_id = 9;
UPDATE departments SET director_AMKA = '66941799670' WHERE dept_id = 10;
UPDATE departments SET director_AMKA = '18398416734' WHERE dept_id = 11;
UPDATE departments SET director_AMKA = '80445092860' WHERE dept_id = 12;
UPDATE departments SET director_AMKA = '90082484581' WHERE dept_id = 13;
UPDATE departments SET director_AMKA = '83997418563' WHERE dept_id = 14;
UPDATE departments SET director_AMKA = '61995305641' WHERE dept_id = 15;

-- staff
LOAD DATA LOCAL INFILE 'data/csv/load/staff_nurses.csv'
INTO TABLE `staff`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(AMKA, first_name, last_name, date_of_birth, email, phone_number, hire_date, staff_type);

-- nurses
LOAD DATA LOCAL INFILE 'data/csv/load/nurses.csv'
INTO TABLE `nurses`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(AMKA, `rank`, dept_id);

-- staff
LOAD DATA LOCAL INFILE 'data/csv/load/staff_admin.csv'
INTO TABLE `staff`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(AMKA, first_name, last_name, date_of_birth, email, phone_number, hire_date, staff_type);

-- admin_staff
LOAD DATA LOCAL INFILE 'data/csv/load/admin_staff.csv'
INTO TABLE `admin_staff`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(AMKA, position, office_location, dept_id);

-- beds
LOAD DATA LOCAL INFILE 'data/csv/load/beds.csv'
INTO TABLE `beds`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(bed_id, dept_id, room_capacity, bed_type);

-- patients
LOAD DATA LOCAL INFILE 'data/csv/load/patients.csv'
INTO TABLE `patients`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(AMKA, first_name, last_name, fathers_name, date_of_birth, gender, weight, height, phone_number, email, address, occupation, nationality, insurance_provider);

-- patient_emergency_contacts
LOAD DATA LOCAL INFILE 'data/csv/load/patient_emergency_contacts.csv'
INTO TABLE `patient_emergency_contacts`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(patient_AMKA, first_name, last_name, phone_number, email, relationship_to_patient);

-- patient_allergies
LOAD DATA LOCAL INFILE 'data/csv/load/patient_allergies.csv'
INTO TABLE `patient_allergies`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(patient_AMKA, substance_id);

-- admissions
LOAD DATA LOCAL INFILE 'data/csv/load/admissions.csv'
INTO TABLE `admissions`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(patient_AMKA, department_id, bed_id, ken_code, admission_date, discharge_date, admission_diagnosis_code, discharge_diagnosis_code);

-- Discharge patients (triggers calculate extra_cost and free beds)
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'H20' WHERE admission_id = 1;
UPDATE admissions SET discharge_date = '2026-04-23', discharge_diagnosis_code = 'W41' WHERE admission_id = 2;
UPDATE admissions SET discharge_date = '2026-03-06', discharge_diagnosis_code = 'Z31.1' WHERE admission_id = 3;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'P74.0' WHERE admission_id = 4;
UPDATE admissions SET discharge_date = '2026-03-27', discharge_diagnosis_code = 'P01' WHERE admission_id = 6;
UPDATE admissions SET discharge_date = '2026-03-22', discharge_diagnosis_code = 'Z65' WHERE admission_id = 7;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'M90.1*' WHERE admission_id = 8;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'A93' WHERE admission_id = 9;
UPDATE admissions SET discharge_date = '2026-03-09', discharge_diagnosis_code = 'S83.4' WHERE admission_id = 10;
UPDATE admissions SET discharge_date = '2026-03-10', discharge_diagnosis_code = 'R26.1' WHERE admission_id = 11;
UPDATE admissions SET discharge_date = '2026-04-29', discharge_diagnosis_code = 'E05.1' WHERE admission_id = 12;
UPDATE admissions SET discharge_date = '2026-04-29', discharge_diagnosis_code = 'A05.0' WHERE admission_id = 13;
UPDATE admissions SET discharge_date = '2026-04-01', discharge_diagnosis_code = 'S69.7' WHERE admission_id = 14;
UPDATE admissions SET discharge_date = '2026-03-16', discharge_diagnosis_code = 'L59.8' WHERE admission_id = 15;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'D73.0' WHERE admission_id = 17;
UPDATE admissions SET discharge_date = '2026-04-12', discharge_diagnosis_code = 'V79.0' WHERE admission_id = 18;
UPDATE admissions SET discharge_date = '2026-04-26', discharge_diagnosis_code = 'H50.0' WHERE admission_id = 19;
UPDATE admissions SET discharge_date = '2026-04-19', discharge_diagnosis_code = 'E87.7' WHERE admission_id = 20;
UPDATE admissions SET discharge_date = '2026-04-10', discharge_diagnosis_code = 'R93.3' WHERE admission_id = 21;
UPDATE admissions SET discharge_date = '2026-03-19', discharge_diagnosis_code = 'D13.5' WHERE admission_id = 22;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'C15.4' WHERE admission_id = 23;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'Z96.7' WHERE admission_id = 24;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'M15.8' WHERE admission_id = 25;
UPDATE admissions SET discharge_date = '2026-03-28', discharge_diagnosis_code = 'Z96.7' WHERE admission_id = 26;
UPDATE admissions SET discharge_date = '2026-03-20', discharge_diagnosis_code = 'Z20.2' WHERE admission_id = 28;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'Z41' WHERE admission_id = 29;
UPDATE admissions SET discharge_date = '2026-04-24', discharge_diagnosis_code = 'M90.1*' WHERE admission_id = 31;
UPDATE admissions SET discharge_date = '2026-04-05', discharge_diagnosis_code = 'Z83.5' WHERE admission_id = 32;
UPDATE admissions SET discharge_date = '2026-03-29', discharge_diagnosis_code = 'C51.9' WHERE admission_id = 33;
UPDATE admissions SET discharge_date = '2026-04-21', discharge_diagnosis_code = 'R46.0' WHERE admission_id = 34;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'N13.7' WHERE admission_id = 35;
UPDATE admissions SET discharge_date = '2026-04-01', discharge_diagnosis_code = 'T52' WHERE admission_id = 36;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'L23.0' WHERE admission_id = 37;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'C93' WHERE admission_id = 38;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'T80.3' WHERE admission_id = 39;
UPDATE admissions SET discharge_date = '2026-03-27', discharge_diagnosis_code = 'N76.6' WHERE admission_id = 40;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'A05.0' WHERE admission_id = 41;
UPDATE admissions SET discharge_date = '2026-04-09', discharge_diagnosis_code = 'J17.0*' WHERE admission_id = 43;
UPDATE admissions SET discharge_date = '2026-03-20', discharge_diagnosis_code = 'T18.2' WHERE admission_id = 44;
UPDATE admissions SET discharge_date = '2026-04-26', discharge_diagnosis_code = 'G44.0' WHERE admission_id = 45;
UPDATE admissions SET discharge_date = '2026-04-12', discharge_diagnosis_code = 'A26.7' WHERE admission_id = 46;
UPDATE admissions SET discharge_date = '2026-03-21', discharge_diagnosis_code = 'S83.4' WHERE admission_id = 47;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'E56.1' WHERE admission_id = 48;
UPDATE admissions SET discharge_date = '2026-04-11', discharge_diagnosis_code = 'C44.3' WHERE admission_id = 49;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'B78.9' WHERE admission_id = 51;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'M36.8*' WHERE admission_id = 54;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'Z31.1' WHERE admission_id = 57;
UPDATE admissions SET discharge_date = '2026-03-21', discharge_diagnosis_code = 'Q44.6' WHERE admission_id = 58;
UPDATE admissions SET discharge_date = '2026-03-25', discharge_diagnosis_code = 'B67.1' WHERE admission_id = 59;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'L23.0' WHERE admission_id = 60;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'C44.9' WHERE admission_id = 61;
UPDATE admissions SET discharge_date = '2026-03-23', discharge_diagnosis_code = 'K56.1' WHERE admission_id = 62;
UPDATE admissions SET discharge_date = '2026-04-01', discharge_diagnosis_code = 'C51.9' WHERE admission_id = 63;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'M14.1*' WHERE admission_id = 64;
UPDATE admissions SET discharge_date = '2026-05-05', discharge_diagnosis_code = 'K67.1*' WHERE admission_id = 65;
UPDATE admissions SET discharge_date = '2026-04-11', discharge_diagnosis_code = 'K06.0' WHERE admission_id = 66;
UPDATE admissions SET discharge_date = '2026-04-18', discharge_diagnosis_code = 'H15.0' WHERE admission_id = 67;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'T22.1' WHERE admission_id = 68;
UPDATE admissions SET discharge_date = '2026-04-27', discharge_diagnosis_code = 'K56.1' WHERE admission_id = 69;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'K72.1' WHERE admission_id = 70;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'R25.2' WHERE admission_id = 71;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'T74.8' WHERE admission_id = 72;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'Z97.4' WHERE admission_id = 73;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'T80.6' WHERE admission_id = 74;
UPDATE admissions SET discharge_date = '2026-04-18', discharge_diagnosis_code = 'J63.4' WHERE admission_id = 75;
UPDATE admissions SET discharge_date = '2026-04-15', discharge_diagnosis_code = 'T45.9' WHERE admission_id = 76;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'S62.4' WHERE admission_id = 77;
UPDATE admissions SET discharge_date = '2026-04-29', discharge_diagnosis_code = 'Z27.0' WHERE admission_id = 78;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'Y57.4' WHERE admission_id = 80;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'V79.0' WHERE admission_id = 81;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'N50.1' WHERE admission_id = 82;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'Y57.4' WHERE admission_id = 83;
UPDATE admissions SET discharge_date = '2026-03-21', discharge_diagnosis_code = 'I64' WHERE admission_id = 84;
UPDATE admissions SET discharge_date = '2026-03-25', discharge_diagnosis_code = 'K83' WHERE admission_id = 85;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'I70.1' WHERE admission_id = 86;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'I70.9' WHERE admission_id = 87;
UPDATE admissions SET discharge_date = '2026-03-23', discharge_diagnosis_code = 'D33.1' WHERE admission_id = 88;
UPDATE admissions SET discharge_date = '2026-05-06', discharge_diagnosis_code = 'C25.2' WHERE admission_id = 89;
UPDATE admissions SET discharge_date = '2026-03-23', discharge_diagnosis_code = 'A01.4' WHERE admission_id = 92;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'J01.2' WHERE admission_id = 93;
UPDATE admissions SET discharge_date = '2026-05-06', discharge_diagnosis_code = 'M85' WHERE admission_id = 94;
UPDATE admissions SET discharge_date = '2026-05-05', discharge_diagnosis_code = 'V19.2' WHERE admission_id = 95;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'H90.4' WHERE admission_id = 97;
UPDATE admissions SET discharge_date = '2026-03-11', discharge_diagnosis_code = 'Z65' WHERE admission_id = 99;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'V85.7' WHERE admission_id = 100;
UPDATE admissions SET discharge_date = '2026-04-29', discharge_diagnosis_code = 'H54.5' WHERE admission_id = 101;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'N93.9' WHERE admission_id = 102;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'Y57.4' WHERE admission_id = 103;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'C15.4' WHERE admission_id = 104;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'J32.0' WHERE admission_id = 105;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'T02.0' WHERE admission_id = 107;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'P01' WHERE admission_id = 108;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'Q13.1' WHERE admission_id = 109;
UPDATE admissions SET discharge_date = '2026-04-21', discharge_diagnosis_code = 'Q44.6' WHERE admission_id = 110;
UPDATE admissions SET discharge_date = '2026-03-13', discharge_diagnosis_code = 'C10.1' WHERE admission_id = 111;
UPDATE admissions SET discharge_date = '2026-04-07', discharge_diagnosis_code = 'D75.2' WHERE admission_id = 112;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'C49' WHERE admission_id = 113;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'Y58.8' WHERE admission_id = 114;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'D30.9' WHERE admission_id = 115;
UPDATE admissions SET discharge_date = '2026-03-15', discharge_diagnosis_code = 'K56.1' WHERE admission_id = 116;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'K13.2' WHERE admission_id = 117;
UPDATE admissions SET discharge_date = '2026-03-09', discharge_diagnosis_code = 'J32.0' WHERE admission_id = 118;
UPDATE admissions SET discharge_date = '2026-04-12', discharge_diagnosis_code = 'K83' WHERE admission_id = 119;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'M14.1*' WHERE admission_id = 120;
UPDATE admissions SET discharge_date = '2026-03-14', discharge_diagnosis_code = 'D21.9' WHERE admission_id = 121;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'F79' WHERE admission_id = 122;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'G93' WHERE admission_id = 123;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'C93' WHERE admission_id = 124;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'L00' WHERE admission_id = 125;
UPDATE admissions SET discharge_date = '2026-04-26', discharge_diagnosis_code = 'K06.0' WHERE admission_id = 127;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'Z72.4' WHERE admission_id = 128;
UPDATE admissions SET discharge_date = '2026-04-01', discharge_diagnosis_code = 'K67.1*' WHERE admission_id = 130;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'C10.1' WHERE admission_id = 131;
UPDATE admissions SET discharge_date = '2026-04-13', discharge_diagnosis_code = 'C96.0' WHERE admission_id = 132;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'T74.8' WHERE admission_id = 133;
UPDATE admissions SET discharge_date = '2026-04-07', discharge_diagnosis_code = 'O24.1' WHERE admission_id = 134;
UPDATE admissions SET discharge_date = '2026-04-05', discharge_diagnosis_code = 'N76.6' WHERE admission_id = 136;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'V87.0' WHERE admission_id = 137;
UPDATE admissions SET discharge_date = '2026-04-26', discharge_diagnosis_code = 'I25.4' WHERE admission_id = 138;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'Z93.8' WHERE admission_id = 139;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'D23.9' WHERE admission_id = 140;
UPDATE admissions SET discharge_date = '2026-04-11', discharge_diagnosis_code = 'S40.7' WHERE admission_id = 141;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'P74.0' WHERE admission_id = 142;
UPDATE admissions SET discharge_date = '2026-04-24', discharge_diagnosis_code = 'K29.6' WHERE admission_id = 143;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'Q91' WHERE admission_id = 144;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'B67.1' WHERE admission_id = 145;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'E86' WHERE admission_id = 148;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'Z86.3' WHERE admission_id = 149;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'M85' WHERE admission_id = 150;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'B95.7' WHERE admission_id = 151;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'O86.0' WHERE admission_id = 152;
UPDATE admissions SET discharge_date = '2026-03-27', discharge_diagnosis_code = 'S40.0' WHERE admission_id = 153;
UPDATE admissions SET discharge_date = '2026-04-22', discharge_diagnosis_code = 'A07.8' WHERE admission_id = 154;
UPDATE admissions SET discharge_date = '2026-03-28', discharge_diagnosis_code = 'A07.8' WHERE admission_id = 155;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'N50.1' WHERE admission_id = 156;
UPDATE admissions SET discharge_date = '2026-04-24', discharge_diagnosis_code = 'O02' WHERE admission_id = 157;
UPDATE admissions SET discharge_date = '2026-04-13', discharge_diagnosis_code = 'C43.9' WHERE admission_id = 158;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'Z61.5' WHERE admission_id = 159;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'M61.0' WHERE admission_id = 160;
UPDATE admissions SET discharge_date = '2026-04-12', discharge_diagnosis_code = 'K73.8' WHERE admission_id = 161;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'H15.9' WHERE admission_id = 162;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'I87.1' WHERE admission_id = 163;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'L65.1' WHERE admission_id = 164;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'K83' WHERE admission_id = 166;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'Q26.0' WHERE admission_id = 167;
UPDATE admissions SET discharge_date = '2026-04-18', discharge_diagnosis_code = 'P01' WHERE admission_id = 168;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'Z08.2' WHERE admission_id = 169;
UPDATE admissions SET discharge_date = '2026-04-03', discharge_diagnosis_code = 'K67.1*' WHERE admission_id = 170;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'Z96.7' WHERE admission_id = 171;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'M40.1' WHERE admission_id = 172;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'A05.0' WHERE admission_id = 173;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'G12.1' WHERE admission_id = 175;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'K14.8' WHERE admission_id = 176;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'O85' WHERE admission_id = 177;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'T80.6' WHERE admission_id = 178;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'C49' WHERE admission_id = 179;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'Z20.2' WHERE admission_id = 180;
UPDATE admissions SET discharge_date = '2026-04-22', discharge_diagnosis_code = 'Y07.1' WHERE admission_id = 181;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'R96' WHERE admission_id = 182;
UPDATE admissions SET discharge_date = '2026-04-10', discharge_diagnosis_code = 'F91.3' WHERE admission_id = 183;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'T45.9' WHERE admission_id = 186;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'C03.0' WHERE admission_id = 187;
UPDATE admissions SET discharge_date = '2026-04-23', discharge_diagnosis_code = 'W41' WHERE admission_id = 188;
UPDATE admissions SET discharge_date = '2026-04-12', discharge_diagnosis_code = 'I07.0' WHERE admission_id = 189;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'V34' WHERE admission_id = 190;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'K22' WHERE admission_id = 191;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'P03.3' WHERE admission_id = 193;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'I05.9' WHERE admission_id = 194;
UPDATE admissions SET discharge_date = '2026-03-22', discharge_diagnosis_code = 'C09.0' WHERE admission_id = 195;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'S35.2' WHERE admission_id = 196;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'I28.1' WHERE admission_id = 197;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'Q67.2' WHERE admission_id = 198;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'I80.8' WHERE admission_id = 199;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'R93.0' WHERE admission_id = 200;
UPDATE admissions SET discharge_date = '2026-04-22', discharge_diagnosis_code = 'C03.0' WHERE admission_id = 201;
UPDATE admissions SET discharge_date = '2026-03-18', discharge_diagnosis_code = 'Z96.7' WHERE admission_id = 202;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'H13.1*' WHERE admission_id = 203;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'I27.2' WHERE admission_id = 206;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'P01.1' WHERE admission_id = 207;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'C77.3' WHERE admission_id = 208;
UPDATE admissions SET discharge_date = '2026-04-23', discharge_diagnosis_code = 'F05.9' WHERE admission_id = 209;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'T03.1' WHERE admission_id = 211;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'T02.0' WHERE admission_id = 212;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'G93' WHERE admission_id = 213;
UPDATE admissions SET discharge_date = '2026-03-03', discharge_diagnosis_code = 'C09.0' WHERE admission_id = 214;
UPDATE admissions SET discharge_date = '2026-04-13', discharge_diagnosis_code = 'S99.7' WHERE admission_id = 215;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'T45.9' WHERE admission_id = 218;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'P05.2' WHERE admission_id = 219;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'L63.1' WHERE admission_id = 220;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'T11.3' WHERE admission_id = 221;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'X96' WHERE admission_id = 222;
UPDATE admissions SET discharge_date = '2026-03-06', discharge_diagnosis_code = 'Z97.4' WHERE admission_id = 223;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'F90.8' WHERE admission_id = 224;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'P14' WHERE admission_id = 225;
UPDATE admissions SET discharge_date = '2026-03-06', discharge_diagnosis_code = 'C48.1' WHERE admission_id = 227;
UPDATE admissions SET discharge_date = '2026-03-21', discharge_diagnosis_code = 'C06.8' WHERE admission_id = 228;
UPDATE admissions SET discharge_date = '2026-03-23', discharge_diagnosis_code = 'T40.1' WHERE admission_id = 229;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'C23' WHERE admission_id = 230;
UPDATE admissions SET discharge_date = '2026-04-19', discharge_diagnosis_code = 'F05.9' WHERE admission_id = 231;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'L59.8' WHERE admission_id = 232;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'X96' WHERE admission_id = 233;
UPDATE admissions SET discharge_date = '2026-03-29', discharge_diagnosis_code = 'S51.0' WHERE admission_id = 234;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'H44' WHERE admission_id = 235;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'L72.2' WHERE admission_id = 236;
UPDATE admissions SET discharge_date = '2026-04-10', discharge_diagnosis_code = 'H20' WHERE admission_id = 237;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'H44' WHERE admission_id = 238;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'H80.2' WHERE admission_id = 240;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'Q44.6' WHERE admission_id = 241;
UPDATE admissions SET discharge_date = '2026-04-25', discharge_diagnosis_code = 'Q62.4' WHERE admission_id = 242;
UPDATE admissions SET discharge_date = '2026-04-11', discharge_diagnosis_code = 'D60.9' WHERE admission_id = 243;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'M90.1*' WHERE admission_id = 245;
UPDATE admissions SET discharge_date = '2026-04-24', discharge_diagnosis_code = 'O32.3' WHERE admission_id = 246;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'A01.4' WHERE admission_id = 247;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'R94' WHERE admission_id = 249;
UPDATE admissions SET discharge_date = '2026-04-09', discharge_diagnosis_code = 'T74.8' WHERE admission_id = 250;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'A44.8' WHERE admission_id = 251;
UPDATE admissions SET discharge_date = '2026-03-28', discharge_diagnosis_code = 'D14.2' WHERE admission_id = 252;
UPDATE admissions SET discharge_date = '2026-03-20', discharge_diagnosis_code = 'H58.1*' WHERE admission_id = 253;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'I41*' WHERE admission_id = 254;
UPDATE admissions SET discharge_date = '2026-04-09', discharge_diagnosis_code = 'Q63.3' WHERE admission_id = 255;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'K72.1' WHERE admission_id = 256;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'S83.4' WHERE admission_id = 257;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'L55.0' WHERE admission_id = 258;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'O24.1' WHERE admission_id = 259;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'Z83.5' WHERE admission_id = 260;
UPDATE admissions SET discharge_date = '2026-03-23', discharge_diagnosis_code = 'C44.3' WHERE admission_id = 261;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'V79.0' WHERE admission_id = 262;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'M77' WHERE admission_id = 263;
UPDATE admissions SET discharge_date = '2026-04-05', discharge_diagnosis_code = 'N50.1' WHERE admission_id = 264;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'K06.0' WHERE admission_id = 265;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'C34.9' WHERE admission_id = 266;
UPDATE admissions SET discharge_date = '2026-04-02', discharge_diagnosis_code = 'W41' WHERE admission_id = 267;
UPDATE admissions SET discharge_date = '2026-04-23', discharge_diagnosis_code = 'F51.3' WHERE admission_id = 268;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'O96' WHERE admission_id = 269;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'W57' WHERE admission_id = 270;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'S69.7' WHERE admission_id = 271;
UPDATE admissions SET discharge_date = '2026-04-15', discharge_diagnosis_code = 'B60.2' WHERE admission_id = 274;
UPDATE admissions SET discharge_date = '2026-03-10', discharge_diagnosis_code = 'Y41.4' WHERE admission_id = 275;
UPDATE admissions SET discharge_date = '2026-04-27', discharge_diagnosis_code = 'R93.3' WHERE admission_id = 276;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'A44.8' WHERE admission_id = 278;
UPDATE admissions SET discharge_date = '2026-03-25', discharge_diagnosis_code = 'J63.4' WHERE admission_id = 279;
UPDATE admissions SET discharge_date = '2026-04-22', discharge_diagnosis_code = 'V19.2' WHERE admission_id = 280;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'G23.0' WHERE admission_id = 282;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'A65' WHERE admission_id = 283;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'J38.3' WHERE admission_id = 284;
UPDATE admissions SET discharge_date = '2026-05-05', discharge_diagnosis_code = 'T03.1' WHERE admission_id = 285;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'K71.9' WHERE admission_id = 286;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'H50.0' WHERE admission_id = 287;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'K06.0' WHERE admission_id = 288;
UPDATE admissions SET discharge_date = '2026-04-08', discharge_diagnosis_code = 'C67' WHERE admission_id = 289;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'O86.0' WHERE admission_id = 290;
UPDATE admissions SET discharge_date = '2026-04-19', discharge_diagnosis_code = 'B40.9' WHERE admission_id = 291;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'C45.9' WHERE admission_id = 292;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'P96.1' WHERE admission_id = 293;
UPDATE admissions SET discharge_date = '2026-04-09', discharge_diagnosis_code = 'K44' WHERE admission_id = 294;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'K67.1*' WHERE admission_id = 295;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'T11.3' WHERE admission_id = 296;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'E56.1' WHERE admission_id = 297;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'D30.9' WHERE admission_id = 298;
UPDATE admissions SET discharge_date = '2026-04-27', discharge_diagnosis_code = 'H54.5' WHERE admission_id = 301;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'O96' WHERE admission_id = 302;
UPDATE admissions SET discharge_date = '2026-04-08', discharge_diagnosis_code = 'M36.8*' WHERE admission_id = 303;
UPDATE admissions SET discharge_date = '2026-04-03', discharge_diagnosis_code = 'M61.0' WHERE admission_id = 306;
UPDATE admissions SET discharge_date = '2026-03-23', discharge_diagnosis_code = 'Z27.0' WHERE admission_id = 307;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'D46.4' WHERE admission_id = 309;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'V88.9' WHERE admission_id = 310;
UPDATE admissions SET discharge_date = '2026-04-19', discharge_diagnosis_code = 'A26.7' WHERE admission_id = 311;
UPDATE admissions SET discharge_date = '2026-03-22', discharge_diagnosis_code = 'N32.8' WHERE admission_id = 312;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'K62.3' WHERE admission_id = 313;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'P03.3' WHERE admission_id = 314;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'H13.1*' WHERE admission_id = 315;
UPDATE admissions SET discharge_date = '2026-03-22', discharge_diagnosis_code = 'T27.7' WHERE admission_id = 317;
UPDATE admissions SET discharge_date = '2026-04-12', discharge_diagnosis_code = 'D26.0' WHERE admission_id = 318;
UPDATE admissions SET discharge_date = '2026-03-27', discharge_diagnosis_code = 'I31.8' WHERE admission_id = 320;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'H50.0' WHERE admission_id = 321;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'O26.8' WHERE admission_id = 322;
UPDATE admissions SET discharge_date = '2026-03-20', discharge_diagnosis_code = 'T33' WHERE admission_id = 323;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'I27.2' WHERE admission_id = 324;
UPDATE admissions SET discharge_date = '2026-03-10', discharge_diagnosis_code = 'E27.1' WHERE admission_id = 325;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'M92.2' WHERE admission_id = 326;
UPDATE admissions SET discharge_date = '2026-03-10', discharge_diagnosis_code = 'M83.1' WHERE admission_id = 327;
UPDATE admissions SET discharge_date = '2026-04-02', discharge_diagnosis_code = 'I61.5' WHERE admission_id = 328;
UPDATE admissions SET discharge_date = '2026-05-05', discharge_diagnosis_code = 'F90.8' WHERE admission_id = 329;
UPDATE admissions SET discharge_date = '2026-04-21', discharge_diagnosis_code = 'S02.6' WHERE admission_id = 330;
UPDATE admissions SET discharge_date = '2026-04-22', discharge_diagnosis_code = 'X18' WHERE admission_id = 331;
UPDATE admissions SET discharge_date = '2026-04-25', discharge_diagnosis_code = 'C04.1' WHERE admission_id = 332;
UPDATE admissions SET discharge_date = '2026-04-15', discharge_diagnosis_code = 'D22.2' WHERE admission_id = 333;
UPDATE admissions SET discharge_date = '2026-03-20', discharge_diagnosis_code = 'Y61.9' WHERE admission_id = 334;
UPDATE admissions SET discharge_date = '2026-04-12', discharge_diagnosis_code = 'C49' WHERE admission_id = 335;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'L02' WHERE admission_id = 336;
UPDATE admissions SET discharge_date = '2026-04-03', discharge_diagnosis_code = 'L00' WHERE admission_id = 337;
UPDATE admissions SET discharge_date = '2026-04-05', discharge_diagnosis_code = 'U88' WHERE admission_id = 338;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'H95.0' WHERE admission_id = 339;
UPDATE admissions SET discharge_date = '2026-03-28', discharge_diagnosis_code = 'Z20.2' WHERE admission_id = 340;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'T62.0' WHERE admission_id = 341;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'P01.1' WHERE admission_id = 342;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'I77.5' WHERE admission_id = 343;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'L02' WHERE admission_id = 344;
UPDATE admissions SET discharge_date = '2026-05-06', discharge_diagnosis_code = 'Z48' WHERE admission_id = 345;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'C44.9' WHERE admission_id = 346;
UPDATE admissions SET discharge_date = '2026-04-26', discharge_diagnosis_code = 'Z65' WHERE admission_id = 348;
UPDATE admissions SET discharge_date = '2026-05-06', discharge_diagnosis_code = 'Z27.0' WHERE admission_id = 349;
UPDATE admissions SET discharge_date = '2026-04-09', discharge_diagnosis_code = 'S83.4' WHERE admission_id = 351;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'F98' WHERE admission_id = 352;
UPDATE admissions SET discharge_date = '2026-04-22', discharge_diagnosis_code = 'Y61.9' WHERE admission_id = 354;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'P94' WHERE admission_id = 355;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'H95.0' WHERE admission_id = 356;
UPDATE admissions SET discharge_date = '2026-04-27', discharge_diagnosis_code = 'E86' WHERE admission_id = 357;
UPDATE admissions SET discharge_date = '2026-04-26', discharge_diagnosis_code = 'L94.2' WHERE admission_id = 358;
UPDATE admissions SET discharge_date = '2026-03-17', discharge_diagnosis_code = 'D13.5' WHERE admission_id = 360;
UPDATE admissions SET discharge_date = '2026-04-13', discharge_diagnosis_code = 'P91.5' WHERE admission_id = 361;
UPDATE admissions SET discharge_date = '2026-04-25', discharge_diagnosis_code = 'Z01.4' WHERE admission_id = 362;
UPDATE admissions SET discharge_date = '2026-03-12', discharge_diagnosis_code = 'K14.8' WHERE admission_id = 363;
UPDATE admissions SET discharge_date = '2026-03-25', discharge_diagnosis_code = 'T27.7' WHERE admission_id = 364;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'K10.3' WHERE admission_id = 365;
UPDATE admissions SET discharge_date = '2026-04-07', discharge_diagnosis_code = 'O32.3' WHERE admission_id = 366;
UPDATE admissions SET discharge_date = '2026-04-01', discharge_diagnosis_code = 'M90.1*' WHERE admission_id = 367;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'P96.1' WHERE admission_id = 368;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'G11.1' WHERE admission_id = 370;
UPDATE admissions SET discharge_date = '2026-04-02', discharge_diagnosis_code = 'C76.8' WHERE admission_id = 371;
UPDATE admissions SET discharge_date = '2026-04-02', discharge_diagnosis_code = 'Z08.2' WHERE admission_id = 372;
UPDATE admissions SET discharge_date = '2026-04-15', discharge_diagnosis_code = 'I01.8' WHERE admission_id = 373;
UPDATE admissions SET discharge_date = '2026-04-18', discharge_diagnosis_code = 'C43.9' WHERE admission_id = 374;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'T29.4' WHERE admission_id = 375;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'M92.2' WHERE admission_id = 376;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'C44.9' WHERE admission_id = 377;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'S62.4' WHERE admission_id = 378;
UPDATE admissions SET discharge_date = '2026-03-07', discharge_diagnosis_code = 'E86' WHERE admission_id = 379;
UPDATE admissions SET discharge_date = '2026-05-10', discharge_diagnosis_code = 'G93' WHERE admission_id = 381;
UPDATE admissions SET discharge_date = '2026-03-18', discharge_diagnosis_code = 'J17.0*' WHERE admission_id = 382;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'F60.7' WHERE admission_id = 383;
UPDATE admissions SET discharge_date = '2026-04-02', discharge_diagnosis_code = 'M17.2' WHERE admission_id = 384;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'O02' WHERE admission_id = 385;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'J17.0*' WHERE admission_id = 386;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'N76.6' WHERE admission_id = 387;
UPDATE admissions SET discharge_date = '2026-04-27', discharge_diagnosis_code = 'T86.2' WHERE admission_id = 388;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'O29' WHERE admission_id = 389;
UPDATE admissions SET discharge_date = '2026-05-06', discharge_diagnosis_code = 'H15.0' WHERE admission_id = 390;
UPDATE admissions SET discharge_date = '2026-04-11', discharge_diagnosis_code = 'I09.9' WHERE admission_id = 391;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'C51.9' WHERE admission_id = 392;
UPDATE admissions SET discharge_date = '2026-03-21', discharge_diagnosis_code = 'L00' WHERE admission_id = 393;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'T19.8' WHERE admission_id = 394;
UPDATE admissions SET discharge_date = '2026-04-03', discharge_diagnosis_code = 'S02.6' WHERE admission_id = 397;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'C09.8' WHERE admission_id = 398;
UPDATE admissions SET discharge_date = '2026-04-29', discharge_diagnosis_code = 'S31.1' WHERE admission_id = 399;
UPDATE admissions SET discharge_date = '2026-04-22', discharge_diagnosis_code = 'D73.0' WHERE admission_id = 400;
UPDATE admissions SET discharge_date = '2026-04-03', discharge_diagnosis_code = 'L72.2' WHERE admission_id = 401;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'J30.3' WHERE admission_id = 402;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'C76.8' WHERE admission_id = 404;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'K22' WHERE admission_id = 405;
UPDATE admissions SET discharge_date = '2026-04-10', discharge_diagnosis_code = 'S42' WHERE admission_id = 407;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'T46.9' WHERE admission_id = 408;
UPDATE admissions SET discharge_date = '2026-04-27', discharge_diagnosis_code = 'T62.2' WHERE admission_id = 409;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'F05.9' WHERE admission_id = 410;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'Z36.5' WHERE admission_id = 412;
UPDATE admissions SET discharge_date = '2026-04-19', discharge_diagnosis_code = 'L00' WHERE admission_id = 413;
UPDATE admissions SET discharge_date = '2026-05-08', discharge_diagnosis_code = 'V30' WHERE admission_id = 414;
UPDATE admissions SET discharge_date = '2026-03-24', discharge_diagnosis_code = 'R96' WHERE admission_id = 415;
UPDATE admissions SET discharge_date = '2026-03-27', discharge_diagnosis_code = 'Y84.7' WHERE admission_id = 416;
UPDATE admissions SET discharge_date = '2026-04-09', discharge_diagnosis_code = 'T43.4' WHERE admission_id = 417;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'T11.3' WHERE admission_id = 418;
UPDATE admissions SET discharge_date = '2026-03-22', discharge_diagnosis_code = 'C48.1' WHERE admission_id = 419;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'O06' WHERE admission_id = 420;
UPDATE admissions SET discharge_date = '2026-04-05', discharge_diagnosis_code = 'Z82.5' WHERE admission_id = 421;
UPDATE admissions SET discharge_date = '2026-04-21', discharge_diagnosis_code = 'S51.0' WHERE admission_id = 422;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'G11.1' WHERE admission_id = 424;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'M83.1' WHERE admission_id = 425;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'R93.0' WHERE admission_id = 428;
UPDATE admissions SET discharge_date = '2026-04-03', discharge_diagnosis_code = 'T44.0' WHERE admission_id = 429;
UPDATE admissions SET discharge_date = '2026-04-19', discharge_diagnosis_code = 'Q26.0' WHERE admission_id = 430;
UPDATE admissions SET discharge_date = '2026-04-02', discharge_diagnosis_code = 'I87.1' WHERE admission_id = 431;
UPDATE admissions SET discharge_date = '2026-03-29', discharge_diagnosis_code = 'V79.0' WHERE admission_id = 432;
UPDATE admissions SET discharge_date = '2026-05-02', discharge_diagnosis_code = 'R96' WHERE admission_id = 433;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'C06.8' WHERE admission_id = 434;
UPDATE admissions SET discharge_date = '2026-03-19', discharge_diagnosis_code = 'I44.2' WHERE admission_id = 435;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'G63.3*' WHERE admission_id = 436;
UPDATE admissions SET discharge_date = '2026-03-25', discharge_diagnosis_code = 'G00.9' WHERE admission_id = 437;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'T23' WHERE admission_id = 438;
UPDATE admissions SET discharge_date = '2026-04-20', discharge_diagnosis_code = 'P91.5' WHERE admission_id = 439;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'G11.1' WHERE admission_id = 440;
UPDATE admissions SET discharge_date = '2026-04-07', discharge_diagnosis_code = 'G99.8*' WHERE admission_id = 441;
UPDATE admissions SET discharge_date = '2026-03-15', discharge_diagnosis_code = 'L41.0' WHERE admission_id = 442;
UPDATE admissions SET discharge_date = '2026-03-21', discharge_diagnosis_code = 'K29.6' WHERE admission_id = 443;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'S27.5' WHERE admission_id = 444;
UPDATE admissions SET discharge_date = '2026-04-15', discharge_diagnosis_code = 'S99.7' WHERE admission_id = 446;
UPDATE admissions SET discharge_date = '2026-04-27', discharge_diagnosis_code = 'I64' WHERE admission_id = 448;
UPDATE admissions SET discharge_date = '2026-03-16', discharge_diagnosis_code = 'M80.4' WHERE admission_id = 449;
UPDATE admissions SET discharge_date = '2026-04-08', discharge_diagnosis_code = 'D26.0' WHERE admission_id = 450;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'M61.0' WHERE admission_id = 451;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'S35.2' WHERE admission_id = 452;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'N74.1*' WHERE admission_id = 453;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'E24.3' WHERE admission_id = 454;
UPDATE admissions SET discharge_date = '2026-05-09', discharge_diagnosis_code = 'I52.1*' WHERE admission_id = 455;
UPDATE admissions SET discharge_date = '2026-04-19', discharge_diagnosis_code = 'Y84.7' WHERE admission_id = 457;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'Y07.1' WHERE admission_id = 458;
UPDATE admissions SET discharge_date = '2026-05-04', discharge_diagnosis_code = 'K29.9' WHERE admission_id = 459;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'H15.0' WHERE admission_id = 460;
UPDATE admissions SET discharge_date = '2026-03-20', discharge_diagnosis_code = 'Q42.3' WHERE admission_id = 461;
UPDATE admissions SET discharge_date = '2026-05-01', discharge_diagnosis_code = 'I09.9' WHERE admission_id = 462;
UPDATE admissions SET discharge_date = '2026-03-31', discharge_diagnosis_code = 'D48' WHERE admission_id = 463;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'Z55.8' WHERE admission_id = 464;
UPDATE admissions SET discharge_date = '2026-04-08', discharge_diagnosis_code = 'K56.1' WHERE admission_id = 465;
UPDATE admissions SET discharge_date = '2026-03-13', discharge_diagnosis_code = 'B18.9' WHERE admission_id = 466;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'T25.0' WHERE admission_id = 467;
UPDATE admissions SET discharge_date = '2026-05-05', discharge_diagnosis_code = 'O24.1' WHERE admission_id = 468;
UPDATE admissions SET discharge_date = '2026-03-22', discharge_diagnosis_code = 'H15.9' WHERE admission_id = 469;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'I23.2' WHERE admission_id = 471;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'I52.1*' WHERE admission_id = 472;
UPDATE admissions SET discharge_date = '2026-05-11', discharge_diagnosis_code = 'D07.6' WHERE admission_id = 473;
UPDATE admissions SET discharge_date = '2026-05-05', discharge_diagnosis_code = 'D22.2' WHERE admission_id = 474;
UPDATE admissions SET discharge_date = '2026-04-14', discharge_diagnosis_code = 'K62.3' WHERE admission_id = 475;
UPDATE admissions SET discharge_date = '2026-04-05', discharge_diagnosis_code = 'E56.0' WHERE admission_id = 476;
UPDATE admissions SET discharge_date = '2026-04-17', discharge_diagnosis_code = 'I01.8' WHERE admission_id = 477;
UPDATE admissions SET discharge_date = '2026-04-11', discharge_diagnosis_code = 'B18' WHERE admission_id = 478;
UPDATE admissions SET discharge_date = '2026-03-19', discharge_diagnosis_code = 'Y61.9' WHERE admission_id = 479;
UPDATE admissions SET discharge_date = '2026-04-04', discharge_diagnosis_code = 'Q62.4' WHERE admission_id = 480;
UPDATE admissions SET discharge_date = '2026-03-18', discharge_diagnosis_code = 'T45.9' WHERE admission_id = 482;
UPDATE admissions SET discharge_date = '2026-04-10', discharge_diagnosis_code = 'C09.0' WHERE admission_id = 483;
UPDATE admissions SET discharge_date = '2026-04-02', discharge_diagnosis_code = 'C81.7' WHERE admission_id = 484;
UPDATE admissions SET discharge_date = '2026-03-26', discharge_diagnosis_code = 'V30' WHERE admission_id = 485;
UPDATE admissions SET discharge_date = '2026-04-24', discharge_diagnosis_code = 'L94.2' WHERE admission_id = 486;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'O24.1' WHERE admission_id = 487;
UPDATE admissions SET discharge_date = '2026-03-06', discharge_diagnosis_code = 'T29.4' WHERE admission_id = 488;
UPDATE admissions SET discharge_date = '2026-03-29', discharge_diagnosis_code = 'K14.1' WHERE admission_id = 489;
UPDATE admissions SET discharge_date = '2026-04-28', discharge_diagnosis_code = 'T45.9' WHERE admission_id = 490;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'I87.1' WHERE admission_id = 491;
UPDATE admissions SET discharge_date = '2026-05-05', discharge_diagnosis_code = 'T80.3' WHERE admission_id = 492;
UPDATE admissions SET discharge_date = '2026-04-10', discharge_diagnosis_code = 'A93' WHERE admission_id = 493;
UPDATE admissions SET discharge_date = '2026-04-06', discharge_diagnosis_code = 'D75.2' WHERE admission_id = 494;
UPDATE admissions SET discharge_date = '2026-04-16', discharge_diagnosis_code = 'E35*' WHERE admission_id = 495;
UPDATE admissions SET discharge_date = '2026-05-03', discharge_diagnosis_code = 'H44.0' WHERE admission_id = 496;
UPDATE admissions SET discharge_date = '2026-03-30', discharge_diagnosis_code = 'Z36.5' WHERE admission_id = 497;
UPDATE admissions SET discharge_date = '2026-05-07', discharge_diagnosis_code = 'R00' WHERE admission_id = 498;
UPDATE admissions SET discharge_date = '2026-03-12', discharge_diagnosis_code = 'F98' WHERE admission_id = 499;
UPDATE admissions SET discharge_date = '2026-04-30', discharge_diagnosis_code = 'Z27.0' WHERE admission_id = 500;

-- triages
LOAD DATA LOCAL INFILE 'data/csv/load/triages.csv'
INTO TABLE `triages`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(patient_AMKA, nurse_AMKA, arrival_time, triage_time, minutes_waited, urgency_level, symptoms, outcome, admission_id);

-- lab_exams
LOAD DATA LOCAL INFILE 'data/csv/load/lab_exams.csv'
INTO TABLE `lab_exams`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(admission_id, exam_code, exam_date, result_text, result_numeric, result_unit, cost, doctor_AMKA);

-- procedure_executions
LOAD DATA LOCAL INFILE 'data/csv/load/procedure_executions.csv'
INTO TABLE `procedure_executions`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(admission_id, procedure_code, room_id, main_doctor_AMKA, start_time, end_time, actual_cost);

-- procedure_assistants
LOAD DATA LOCAL INFILE 'data/csv/load/procedure_assistants.csv'
INTO TABLE `procedure_assistants`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(execution_id, staff_AMKA, `role`);

-- prescriptions
LOAD DATA LOCAL INFILE 'data/csv/load/prescriptions.csv'
INTO TABLE `prescriptions`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(admission_id, patient_AMKA, doctor_AMKA, drug_id, dosage, frequency, start_date, end_date);

-- admission_ratings
LOAD DATA LOCAL INFILE 'data/csv/load/admission_ratings.csv'
INTO TABLE `admission_ratings`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(admission_id, nursing_quality, cleanliness, food, overall, comment, rated_at);

-- doctor_ratings
LOAD DATA LOCAL INFILE 'data/csv/load/doctor_ratings.csv'
INTO TABLE `doctor_ratings`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(admission_id, doctor_AMKA, medical_care_quality, comment, rated_at);

-- shifts
LOAD DATA LOCAL INFILE 'data/csv/load/shifts.csv'
INTO TABLE `shifts`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(shift_id, shift_date, shift_slot, shift_status, dept_id);

-- shift_staffing
LOAD DATA LOCAL INFILE 'data/csv/load/shift_staffing.csv'
INTO TABLE `shift_staffing`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(shift_id, staff_AMKA);

-- department_images
LOAD DATA LOCAL INFILE 'data/csv/load/department_images.csv'
INTO TABLE `department_images`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(dept_id, img_url, caption, ordering);

-- drug_images
LOAD DATA LOCAL INFILE 'data/csv/load/drug_images.csv'
INTO TABLE `drug_images`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(drug_id, img_url, caption, ordering);

-- doctor_images
LOAD DATA LOCAL INFILE 'data/csv/load/doctor_images.csv'
INTO TABLE `doctor_images`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(doctor_AMKA, img_url, caption, ordering);

-- Done.
